### ISSUE TITLE
[FIX] HDMI Audio

### ISSUE THREAD

**Issue by arvedviehweger** [danieleds/Asus-UX32VD-Hackintosh#1]
Hello,

I have the same Laptop and I could fully fix the HDMI Audio. 

Here is the fix in my fork of your repo: https://github.com/haimann951/Asus-UX32VD-Hackintosh/commit/84ac785ea36dc1265818efe3203487fe3954371d

Thanks for all the stuff you already did.

**Comment by danieleds** [comment]
Thank you! :)
I tried to apply your patch but my zenbook reboots as soon as I plug the HDMI cable. If I start OS X with the cable plugged, it reboots as soon as it can. (Without the patch, HDMI video works)

Did you change anything else, maybe in your DSDT? Is your standard (non-HDMI) audio working with my patches and kexts?

@diegobit am I wrong, or you had a similar issue time ago?

**Comment by diegobit** [comment]
I had... actually, I still have this issue. I never use HDMI so I forgot about it, but I'll try to fix it and if I find a good method, I'll let you know. Anyway, my case may be different since I don't have a discrete GPU. 

Are your Intel HD4000 `Audio Device ID` and `Codec ID` the same?

**Comment by danieleds** [comment]
This is my audio info from DCPIManager. @haimann951, can we compare?

![codec](https://s32.postimg.org/8hoj0ct51/audioinfo.png)

**Comment by arvedviehweger** [comment]
I patched my AppleHDA with the AppleHDA Patcher for the ALC269VB Codec. That worked without any problems. I might have added one Patch to the DSDT, I'll check that once I'm back home tommorow. It would be useful if you could send me an iOReg of your System, so that I can compare exactly that.

**Comment by danieleds** [comment]
Here it is: http://pastebin.com/F4YHkyCC

**Comment by danieleds** [comment]
Okay, I managed to resolve the issue relative to the reboot. I had to replace my old manual patch with the `aDummyHDA.kext` generated by AppleHDA Patcher (choosing `Realteck ALC 269 VB v1`).

Within tomorrow I will be able to actually test the HDMI audio.

**Comment by danieleds** [comment]
@haimann951 your patch works like a charm. I have updated the repository.
Thanks :)
